-- LOCATION DIMENSION table
drop table if exists location_dim cascade;
create table location_dim ( 
location_dim_id     bigint generated by default as identity(1, 1), 
location_key        bigint distkey, 
address             character varying(255), 
street              character varying(255), 
postcode            character varying(20), 
state               character varying(50), 
suburb              character varying(100),
track_hash          bigint, 
record_start_ts varchar(25), 
record_end_ts varchar(25), 
record_active_flag  smallint default 1, 
record_upd_ts varchar(25), 
record_insert_ts varchar(25),)
diststyle key 
sortkey (location_key);

-- PROCEDURE DIMENSION table
drop table if exists procedure_dim cascade;
create table procedure_dim ( 
procedure_dim_id   bigint generated by default as identity(1, 1), 
procedure_key      bigint distkey, 
procedure          character varying(255), 
track_hash         bigint, 
record_start_ts varchar(25), 
record_end_ts varchar(25), 
record_active_flag smallint default 1, 
record_upd_ts varchar(25), 
record_insert_ts varchar(25),)
diststyle key 
sortkey (procedure_key);

-- PROVIDER DIMENSION table
drop table if exists provider_dim cascade;
create table provider_dim ( 
provider_dim_id           bigint generated by default as identity(1, 1), 
provider_key              bigint distkey, 
location_key              bigint, 
provider_license_number   character varying(100), 
provider_id               integer, 
provider_name             character varying(255), 
provider_phone_number     character varying(25), 
provider_email_address    character varying(255), 
provider_type             character varying(100),
track_hash                bigint, 
record_start_ts varchar(25), 
record_end_ts varchar(25), 
record_active_flag        smallint default 1, 
record_upd_ts varchar(25), 
record_insert_ts varchar(25),)
diststyle key 
sortkey (provider_key);

-- POLICYHOLDER DIMENSION TABLE
drop table if exists policyholder_dim cascade;
create table policyholder_dim ( 
policyholder_dim_id    bigint generated by default as identity(1, 1), 
policyholder_key       bigint distkey, 
location_key           bigint, 
policyholder_id        integer, 
first_name             character varying(100), 
last_name              character varying(100), 
gender                 character varying(10), 
phone_number           character varying(25), 
email_address          character varying(255), 
date_of_birth          date, 
insurance_plan_details character varying(255), 
policy_standing        character varying(100), 
coverage_start_date    date,
coverage_end_date      date,
track_hash             bigint, 
record_start_ts varchar(25), 
record_end_ts varchar(25), 
record_active_flag     smallint default 1, 
record_upd_ts varchar(25), 
record_insert_ts varchar(25),)
diststyle key 
sortkey (policyholder_key);

-- DATE DIMENSION table
drop table if exists date_dim cascade;
create table date_dim (
date_key             bigint generated by default as identity(1, 1),
date                 timestamp,
day_of_week          bigint,
day_name             character varying(20),
day_of_month         bigint,
day_of_year          bigint,
week_of_year         bigint,
month                bigint,
month_name           character varying(20),
quarter              bigint,
year                 bigint,
is_weekend           boolean,
is_weekday           boolean,
is_holiday           boolean,
track_hash           bigint,
record_start_ts varchar(25),
record_end_ts varchar(25),
record_active_flag   smallint default 1,
record_upd_ts varchar(25),
record_insert_ts varchar(25),)
diststyle all 
sortkey (date_key);